#!/usr/bin/env python3
import os
import subprocess
from pathlib import Path
from joblib import Parallel, delayed

# =============================
# CONFIGURATION DES PARAMETRES
# =============================
# taux de OC formation
base = [round(i*0.2, 2) for i in range(1, 51)]

# adding extra values
extras = [0.04, 0.08, 0.15, 0.32, 3.62]

# Junction between extra + base
ko_values = sorted(set(base + extras))

# taux de unbinding de TopoI 
kun_values  = [1e-6, 1e-5, 1e-4, 1e-3, 5e-3, 1e-2, 3e-2, 5e-2, 0.08, 1e-1, 0.12, 0.15, 0.2, 0.3, 0.4, 5e-1, 0.7, 0.8, 1, 1.3, 1.5, 2, 5, 10]
# distânces TSS 
#tss_values  = [50, 100, 200, 250, 300, 500, 750, 1000, 1500, 2000, 3000, 4000, 5000]

# fixex
kb_value = 0.453
so_value = -0.04
ke_value = 100
Ld_value = 520
tss_value = 1000

# Number of processes in paralelel 
n_jobs = 48

# Way to twin.py
twin_script = Path("bin") / "twin.py"

def run_simulation(ko, kun, tss):
    outdir = Path("results_jobs2") / f"ko_{ko}" / f"kun_{kun}" #/ f"tss_{tss}"
    outdir.mkdir(parents=True, exist_ok=True)

    cmd = [
        "python3", str(twin_script), str(outdir),
        "-f",
        # parametres FIXES
        "-kb", str(kb_value),
        "-so", str(so_value),
        "-ke", str(ke_value),
        "-Ld", str(Ld_value),
        "-tss", str(tss_value),
        # parâmetros VARIÁVEIS
        "-ko", str(ko),
        "-ku", str(kun),
        "-tss", str(tss),
        "-Nt", "10000",    # maximum de transcripts
              
    ]

    proc = subprocess.run(cmd, capture_output=True, text=True)
    return ko, kun, tss, proc.returncode, proc.stdout, proc.stderr

if __name__ == "__main__":
    # Create the combinations
    combos = [
        (ko, kun) #tss)
        for ko in ko_values
        for kun in kun_values
        #for tss in tss_values
    ]

    # executer en paralelel
    results = Parallel(n_jobs=n_jobs)(
        delayed(run_simulation)(ko, kun) #tss)
        for ko, kun,  in combos #tss
    )

    # relatório final
    # print("\n=== RESUMÉ DES SIMULATIONS ===")
    # for ko, kun, code, out, err in results: #tss
    #     tag = f"ko={ko:<5} kun={kun:<6} tss={tss:<3}"
    #     if code != 0:
    #         print(f"[ ERREUR ] {tag} ➞ exit code {code}")
    #         print(err)
    #     else:
    #         print(f"[   OK  ] {tag}")
    # print("\nTOUTES LES SIMULATIONS SONT FINIES")